### ISSUE TITLE
errors found in log relating to storagedrawersextras

### ISSUE THREAD

**Issue by Hellcommander** [jaquadro/StorageDrawersExtras#9]
Found errors relating to Storagedrawersextras
`[16:11:13] [main/ERROR] [FML/]: Exception loading model for variant storagedrawersextra:extra_trim_3#meta=15
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model storagedrawersextra:extra_trim_3#meta=15 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:233) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:166) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cga.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cet.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:83) ~[bvt.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1208) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 15 more
[16:11:13] [main/ERROR] [FML/]: Exception loading blockstate for the variant storagedrawersextra:extra_trim_3#meta=15: 
java.lang.Exception: Could not load model definition for variant storagedrawersextra:extra_trim_3
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:266) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:129) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cga.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cet.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model storagedrawersextra:blockstates/extra_trim_3.json
	at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:251) ~[cfz.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:231) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:262) ~[ModelLoader.class:?]
	... 14 more
Caused by: java.io.FileNotFoundException: storagedrawersextra:blockstates/extra_trim_3.json
	at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:104) ~[ceg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:79) ~[cet.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:244) ~[cfz.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:231) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:262) ~[ModelLoader.class:?]
	... 14 more
[16:11:13] [main/ERROR] [FML/]: Exception loading model for variant storagedrawersextra:extra_trim_3#meta=12
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model storagedrawersextra:extra_trim_3#meta=12 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:233) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:166) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cga.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cet.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:83) ~[bvt.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1208) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 15 more
[16:11:13] [main/ERROR] [FML/]: Exception loading model for variant storagedrawersextra:extra_trim_3#meta=13
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model storagedrawersextra:extra_trim_3#meta=13 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:233) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:166) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cga.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cet.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:83) ~[bvt.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1208) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 15 more
[16:11:13] [main/ERROR] [FML/]: Exception loading model for variant storagedrawersextra:extra_trim_3#meta=14
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model storagedrawersextra:extra_trim_3#meta=14 with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:233) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:166) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cga.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cet.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:83) ~[bvt.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1208) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 15 more`

**Comment by jaquadro** [comment]
what version of the mod, and which supported mods do you also have (e.g. BoP, Natura, Forestry)

**Comment by Hellcommander** [comment]
BoP and was using the latest version for 1.12 (for both of them) versions: version are BiomesOPlenty-1.12-7.0.0.2289-universal.jar for bop and StorageDrawersExtras-1.12-3.1.0.jar for storagedrawers extras
